// examples/hippy-react-demo/src/externals/DyanmicImport/AsyncComponent.jsx
import React from 'react';
import {
  View,
  StyleSheet,
} from '@hippy/react';

const styleObj = StyleSheet.create({
  asyncComponentDemo: {
    display: 'flex',
    alignItems: 'center',
    position: 'relative',
    height: 300,
    width: 400,
    backgroundColor: '#0055f0',
  },
});

const AsyncComponent = () => (
  <View style={styleObj.asyncComponentDemo}>
    我是异步组件
  </View>
);

export default AsyncComponent;

// examples/hippy-vue-demo/src/components/demos/dynamicImport/async-component.vue
<template>
  <div id="asynccomponent">
    <label>我是异步组件</label>
  </div>
</template>

<script>
export default {
  data() {
    return {
    };
  },
};
</script>

<style>
  #asynccomponent {
    display: flex;
    flex-direction: column;
    align-items: center;
    position: relative;
    height: 300;
    width: 400;
    background-color: #0055f0;
  }
</style>
